on:
  push:
    branches: [main]
  schedule:
    - cron: '0 1 * * *'

permissions:
  contents: write

name: Render observationsliste_datalab

jobs:
  render:
    name: Render observationsliste_datalab
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev
          sudo apt-get install -y libfreetype6-dev libpng-dev libtiff5-dev libjpeg-dev
          sudo apt-get install -y libfontconfig1-dev libfreetype6-dev libfribidi-dev libharfbuzz-dev

      - name: Install packages
        run: |
          Rscript -e 'install.packages(c("rmarkdown","curl","knitr","kableExtra","formattable","systemfonts","textshaping","ragg","here","tidyverse","plotly","httr","readr","openssl","zoo"), repos="https://cloud.r-project.org")'

      - name: Render observationsliste_datalab
        env:
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: Rscript -e 'rmarkdown::render("observationslisten.Rmd", output_format = "html_document")'

      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add -A .
          git commit -m "[skip ci] Re-build observationslisten.html" || echo "No changes to commit"

      - name: Pull (rebase) and push
        run: |
          git pull --rebase origin main || git rebase --abort
          git push origin HEAD:main || echo "No changes to push"
